# To trigger a Travis-CI build for every GitHub push or Pull Request:
# 1. Goto https://travis-ci.org/profile/3D-e-Chem
# 2. Flip the switch for the `knime-silicos-it` repo
sudo: false
language: java
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
   script: xvfb-run mvn verify -B
 - os: osx
   osx_image: xcode8.2
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
install: mvn package -B
script:
- mvn verify -B
- mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

