# To trigger a Travis-CI build for every GitHub push or Pull Request:
# 1. Goto https://travis-ci.org/profile/3D-e-Chem
# 2. Flip the switch for the `knime-silicos-it` repo
sudo: false
language: java
matrix:
 include:
 - os: linux
   jdk: oraclejdk8
   addons:
    apt:
      packages:
      - metacity
   env: DISPLAY=:99.0
   script: 
   - export DISPLAY=:5009
   - "sh -e /etc/init.d/xvfb start"
   - metacity --sm-disable --replace 2> metacity.err &
   - mvn verify -B
   - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
 - os: osx
   osx_image: xcode8.3
   script: Xvfb :5009 & export DISPLAY=:5009 && mvn verify -B
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
before_cache:
  - rm -fr $HOME/.m2/repository/nl/esciencecenter/e3dchem/knime/silicosit
cache:
  directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
install: mvn package -B

